import type { AuthInstance } from "@rave/auth";
import type { Database } from "@rave/db";

import {
  ballotRoute,
  PORTAL_ROUTES,
  peerScoresRoute,
} from "../features/portal/paths";
import { issueCredentialHeaders, type SeededCredentials } from "./credentials";
import { loadFixtures } from "./fixtures";
import {
  SEED_PASSWORD,
  type SeedAccounts,
  type SeedCounts,
  seedFixtures,
} from "./seed";

export type { SeededCredentials } from "./credentials";
// biome-ignore lint/performance/noBarrelFile: seed entry point re-exporting its collaborators
export { type Fixtures, loadFixtures } from "./fixtures";
export type { SeedAccounts, SeedCounts } from "./seed";
export { SEED_PASSWORD, seedFixtures } from "./seed";

export interface SeedSummary {
  accounts: SeedAccounts;
  counts: SeedCounts;
  credentials: SeededCredentials;
  eventId: string;
  fixturesPath: string;
  notes: string[];
}

export interface RunSeedOptions {
  auth: AuthInstance;
  db: Database;
  log: (message: string) => void;
}

/**
 * Seeds the shared fixture and returns working credentials for each role.
 *
 * Runs on every server boot, so it must stay safe to repeat: inserts ignore
 * conflicts and each boot prints a freshly signed cookie per role without
 * invalidating the ones already handed out.
 *
 * @param options - Database and auth handles, plus a logger
 * @returns Seeded accounts, row counts, the four auth headers, and any skipped
 *   fixture rows
 */
export async function runSeed({
  auth,
  db,
  log,
}: RunSeedOptions): Promise<SeedSummary> {
  const { fixtures, path } = loadFixtures();
  const { accounts, counts, notes } = await seedFixtures(db, fixtures, log);
  const credentials = await issueCredentialHeaders(auth, accounts);

  for (const note of notes) {
    log(`seed note: ${note}`);
  }

  return {
    accounts,
    counts,
    credentials,
    eventId: fixtures.event.id,
    fixturesPath: path,
    notes,
  };
}

/** The sign-in headers, in the shape the acceptance spec describes. */
export function formatLoginBlock(credentials: SeededCredentials): string {
  return [
    "seeded. test logins:",
    `  organizer    ${credentials.organizer}`,
    `  judge_a      ${credentials.judgeA}`,
    `  judge_b      ${credentials.judgeB}`,
    `  participant  ${credentials.participant}`,
    "",
    `sign in at the web app with any seeded email and password "${SEED_PASSWORD}"`,
  ].join("\n");
}

/**
 * Renders `.dogfood.toml`.
 *
 * Both the auth headers and the route paths come from live state, so the
 * generated file cannot drift from the running portal.
 *
 * @param credentials - Auth headers produced by the seed
 * @param accounts - Seeded accounts, for the peer-scores URL
 * @param baseUrl - Where the portal is reachable
 */
export function renderDogfoodToml(
  credentials: SeededCredentials,
  accounts: SeedAccounts,
  baseUrl: string,
  eventId: string
): string {
  return `# Generated by \`bun run seed:config\`. Do not hand-edit: re-run the
# command to refresh it, or the acceptance checker will probe stale routes.

[portal]
base_url = "${baseUrl}"

[tiers]
claimed = ["T1", "T2"]
pitch = "Hackathon submission and judging platform: teams submit projects, organizers assign judges, judges score against a weighted rubric without ever seeing each other's work."

[auth]
# Cookies issued by the seed. The checker attaches these instead of logging in.
organizer   = "${credentials.organizer}"
judge_a     = "${credentials.judgeA}"
judge_b     = "${credentials.judgeB}"
participant = "${credentials.participant}"

[routes]
gallery      = "${PORTAL_ROUTES.gallery}"
submit       = "${PORTAL_ROUTES.submit}"
judge_scores = "${PORTAL_ROUTES.judgeScores}"
# The URL that returns judge_a's scores. The checker visits it as judge_b.
peer_scores  = "${peerScoresRoute(accounts.judgeA.id)}"
csv_export   = "${PORTAL_ROUTES.csvExport}"
# The server-rendered, no-JavaScript ballot for community voting.
ballot       = "${ballotRoute(eventId)}"
`;
}
