import { pgEnum, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const roleEnum = pgEnum("user_role", [
  "visitor",
  "participant",
  "judge",
  "organizer",
  "admin",
]);

// Extend the base user table generated by better-auth with a role column.
// We use a separate table so better-auth schema generation stays clean.
export const userProfile = pgTable("user_profile", {
  avatarUrl: text("avatar_url"),
  bio: text("bio"),
  githubUrl: text("github_url"),
  role: roleEnum("role").notNull().default("participant"),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  userId: text("user_id").primaryKey(),
  websiteUrl: text("website_url"),
});
